### ISSUE TITLE
linearGradient error（Undefined PreferNativeSvgSupport）

### ISSUE THREAD

**Issue by SteveQi** [EtheaDev/SVGIconImageList#104]
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   height="800"
   width="1280"
   version="1.1">

  <defs>

    <linearGradient
       y2="67.370003"
       x2="196.10001"
       y1="116.5"
       x1="167.5"
       gradientTransform="translate(49.05624,176.24487)"
       gradientUnits="userSpaceOnUse"
       id="linearGradient2833"
       xlink:href="#linearGradient4944" />
    <linearGradient
       id="linearGradient4944"
       y2="67.370003"
       gradientUnits="userSpaceOnUse"
       x2="196.10001"

       y1="116.5"
       x1="167.5">
      <stop
         id="stop3448"
         offset="0" />
      <stop
         id="stop3450"
         stop-color="#f5f5f5"
         stop-opacity=".9608"
         offset="1" />
    </linearGradient>
  </defs>

    <rect
       style="fill:#053cac;stroke:url(#linearGradient2833);stroke-width:10"
       id="rect2829"
       height="25"
       width="60"
       y="240"
       x="220" />

</svg>

**Comment by pyscripter** [comment]
I have submitted a PR that deals with the stroke width (expand the gradient are by half  the stroke width).

However the issue with the above svg is that the gradient does not cover the shape and is padded.
You will find in the source code a note saying:
  {
    SpreadMethod is not implemented
    Assumed to be repeat for LinearGradient and pad for RadialGradient
  }
The reason it is not implemented is that is kind of hard to do with GDI+

However if the gradient area is equal or larger than the filled are it should work.  In most svgs  probably including yours, when this is not the case it is by accident and not by design.  For example the following svg now renders fine:

```svg
<svg 
  xmlns:xlink="http://www.w3.org/1999/xlink"
  viewBox="200 230 100 60">

<linearGradient
   y2="245"
   x2="260"
   y1="220"
   x1="200"
   gradientTransform="translate(20,20)"
   gradientUnits="userSpaceOnUse"
   id="linearGradient2833"
   xlink:href="#linearGradient4944" />
<linearGradient
   id="linearGradient4944">
  <stop
     id="stop3448"
     offset="0" />
  <stop
     id="stop3450"
     stop-color="#f5f5f5"
     stop-opacity=".9608"
     offset="1" />
</linearGradient>


<rect
   style="fill:#053cac;stroke:url(#linearGradient2833);stroke-width:10"
   id="rect2829"
   height="25"
   width="60"
   y="240"
   x="220" />
</svg>
```

It is easier to use the default gradientUnits and use percentages to fill the area:

```svg
<svg 
  xmlns:xlink="http://www.w3.org/1999/xlink"
  viewBox="200 230 100 60">

<linearGradient
   y1="0"
   x1="0"
   y2="1"
   x2="1"
   id="linearGradient2833"
   xlink:href="#linearGradient4944" />
<linearGradient
   id="linearGradient4944">
  <stop
     id="stop3448"
     offset="0" />
  <stop
     id="stop3450"
     stop-color="#f5f5f5"
     stop-opacity=".9608"
     offset="1" />
</linearGradient>


<rect
   style="fill:#053cac;stroke:url(#linearGradient2833);stroke-width:10"
   id="rect2829"
   height="25"
   width="60"
   y="240"
   x="220" />
</svg>

```
