### ISSUE TITLE
Make svg rendering engine replaceable

### ISSUE THREAD

**Issue by vincentparrett** [EtheaDev/SVGIconImageList#13]
Currently it's tied to GDI+ which is not working too well with lots of svg images. Literally the first image I tried did not render correctly.

![svgfail](https://user-images.githubusercontent.com/1037262/88253757-64992280-ccf6-11ea-8b10-df014f5910b9.png)

Ideally there would an interface that can be implemented to wrapper different svg engines.

I really wanted to use this library, as working with png's at multiple sizes is just too much work, but it fails on too many of my images (mostly from axialis so I cannot share them for testing with).

**Comment by carloBarazzetta** [comment]
Hi Vincent, the purpose of these components is to use only free / opensource components, so I would like to correct this rendering error at the level of the SVG library used internally (that is not mine, it was written by Martin Walter )...
Can you give me the svg code of this icon to understand where the problem lies? Could be a simple fix.

**Comment by vincentparrett** [comment]
I image is not open source so I cannot post the svg here. I can send you a copy privately (let me know how).

**Comment by pyscripter** [comment]
Windows includes basic support for SVG parsing and rendering since the Windows 10 Creators Update:

Info: https://docs.microsoft.com/en-us/windows/win32/direct2d/svg-support
C++ demo https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/d2dsvgimage/

It would be nice to have the option to use the built-in Windows support if it is available.

**Comment by pyscripter** [comment]
See https://en.delphipraxis.net/topic/3215-native-svg-parsing-and-painting-in-windows/

**Comment by carloBarazzetta** [comment]
@vincentparrett  can you send me carlo.barazzetta@ethea.it some svg examples with rendering problems?

**Comment by vincentparrett** [comment]
Sent.

**Comment by carloBarazzetta** [comment]
For rendering problems, try with this fix into 
function GetSVGColor(const ASVGColorName: string): TColor; 
and send me a feed-back:

  if ASVGColorName = '' then
  begin
    Result := -1;
    Exit;
  end;
  //START: LINES ADDED
  if SameText(ASVGColorName, 'none') then
  begin                                                            
    Result := SVG_NONE_COLOR;
    Exit;
  end;
  //END

**Comment by carloBarazzetta** [comment]
![image](https://user-images.githubusercontent.com/7803548/89014818-61b1b980-d316-11ea-80ed-462cdc2991a7.png)

**Comment by vincentparrett** [comment]
Yes! That does fix it, nice one!
