### ISSUE TITLE
base64 encoded svg didn't display  in ver 3.0.0

### ISSUE THREAD

**Issue by frankwu-delphi** [EtheaDev/SVGIconImageList#199]
base64 encoded svg didn't display  in SVGIconImageList ver 3.0.0, 
but same svg correctly display in SVGIconImageList ver 2.2.0.

base64 encoded svg sample:
[edge svg with base64 .zip](https://github.com/EtheaDev/SVGIconImageList/files/7153198/edge.svg.with.base64.zip)

**Comment by carloBarazzetta** [comment]
Check for the changed default of the engine used in 2.2.0 (TSVG) and in 3.0.0 (Image32).
[Here](https://github.com/EtheaDev/SVGIconImageList/wiki/Choice-of-Factories) you can read some details.
Probably base64 encoding is not yet supported in Image32, you can "switch" to TSVG engine, at the moment...

**Comment by carloBarazzetta** [comment]
I noticed that the svg image contained in edge svg base64.zip is a png embedded in an SVG - it is a bad idea to use this type of file because the "resize function" of an SVG image is completely lost.
![image](https://user-images.githubusercontent.com/7803548/133066221-2590feb7-f3d1-49ac-a4fa-7a1ba18cc847.png)

**Comment by frankwu-delphi** [comment]
@carloBarazzetta
thank you for quick reply.

**Comment by pyscripter** [comment]
Please keep open so that Image32 fixes this.

**Comment by AngusJohnson** [comment]
Noted thanks but it's low priority for the reason stated by Carlo.
