### ISSUE TITLE
DPI parameter

### ISSUE THREAD

**Issue by insp63** [EtheaDev/SVGIconImageList#243]
Delphi 10.3 - When the DPI parameter is set to 125%, the icons increase as if it is an ordinary picture and not an SVG. It is possible because of the set values of height and width. The icon is stretched by means of Windows and not by means of Delphi
![100% dpi](https://user-images.githubusercontent.com/7989354/190066555-8b159cb5-6ee1-4fb7-9dcb-9d467bf9064b.png)
![125% dpi](https://user-images.githubusercontent.com/7989354/190066557-01973814-c8f7-4e3e-8e6e-877ca0114866.png)
![settings](https://user-images.githubusercontent.com/7989354/190066558-a7b866f6-a2bc-495d-8ca9-bcc652e9115b.png)

**Comment by carloBarazzetta** [comment]
Hello, in the VCL implementation, using VirtualImageList and SvgIconImageCollection, the icons are painted at the VirtualImageList size, because VirtualImageList scales automatically by TVirtualImageList.DPIChangedMessageHandler.
When the size of the virtualimagelist changes, the icons are repainted at the correct size.
Are you using VirtualImageList/SvgIconImageCollection like explained here?
[wiki/Virtual-image-collection](https://github.com/EtheaDev/SVGIconImageList/wiki/Virtual-image-collection)
Look those two pictures, of the Demo application, the first with 100% dpi and the second with 150% dpi: the VirtualImageList placed on main form scales automatically.
![image](https://user-images.githubusercontent.com/7803548/190078260-4bfa6ed6-c949-486d-859d-892598070412.png)
![image](https://user-images.githubusercontent.com/7803548/190078294-0b151162-c69d-46e5-a46e-64d8bad36a54.png)

**Comment by insp63** [comment]
Thanks. As soon as I put VirtualImageList everything worked out
