### ISSUE TITLE
TSVGIconImage + WrapMode

### ISSUE THREAD

**Issue by kazuser** [EtheaDev/SVGIconImageList#252]
Is it ok?

![image](https://user-images.githubusercontent.com/3335273/211585287-d23a4540-f736-4114-9557-33c04111913b.png)

**Comment by carloBarazzetta** [comment]
I've no control over the "size" inside SVG text of the image, because my component ask to the SVG engine to paint the image inside the area of the SVGIconImage: the intent of using a scalable images format is to scale them... If you want to paint the image in a different size you can use the BitmapZoom property to reduce the dimension of the image.
