### ISSUE TITLE
Image not drawn completly

### ISSUE THREAD

**Issue by jfudickar** [EtheaDev/SVGIconImageList#254]
Have a look at this SVG file (generated from plantuml).
In the legend at the end there are empty coloured rectangles which are not drawn in delphi :
![grafik](https://user-images.githubusercontent.com/3485451/224549564-c81e61ca-6afa-431a-8f5e-a69fd2548028.png)
but drawn when showing the file in the edge browser:
![spacex_launch_latest compact](https://user-images.githubusercontent.com/3485451/224549327-5f297927-e1ce-492b-94d3-dbeb6382c9a3.svg)

Regards
Jens

**Comment by carloBarazzetta** [comment]
Please attach the SVG file...

**Comment by jfudickar** [comment]
It must be attached somehow, because I dragged it in.
Try the right mouse click on the big image and save as.

**Comment by jfudickar** [comment]
Should be here : https://user-images.githubusercontent.com/3485451/224549327-5f297927-e1ce-492b-94d3-dbeb6382c9a3.svg

**Comment by carloBarazzetta** [comment]
I've notice that the problem are in those 4 lines: adding an 'X' instead of three spaces shows the X with correct background color...
`<text fill="#000000" filter="url(#bz2wwsoabm0qe0)" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="12" x="826.5" y="1801.0332">X</text>
<text fill="#000000" filter="url(#bz2wwsoabm0qe1)" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="12" x="945.5" y="1801.0332">X</text>
<text fill="#000000" filter="url(#bz2wwsoabm0qe2)" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="12" x="1032.5" y="1801.0332">X</text>
<text fill="#000000" filter="url(#bz2wwsoabm0qe3)" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="12" x="1102.5" y="1801.0332">X</text>
`
Maybe an incorrect use of background text color for spaces, in Image32 SVG Library of Angus:
https://github.com/AngusJohnson/Image32

**Comment by jfudickar** [comment]
Will you raise a ticket there?
I can't work with the X :-)

**Comment by AngusJohnson** [comment]
Hi Jens. I can confirm there is a bug in Image32's SVG reader, but I can't see an _easy_ fix.
While I've only had a quick look so far, the issue seems to be related to getting the correct bounds of the floodfill filter element.

**Comment by jfudickar** [comment]
Hi Angus, I have not a real problem with it.
The delphi implementation is only a "nice to have" of my json2puml project.
Most of the people will work with the svg file directly.
But I wanted to mention it :-)

**Comment by AngusJohnson** [comment]
Here's a 'quick and dirty' solution ...

In TShapeElement.Draw() in Img32.SVG.Reader @ line ~2100 

```
    //get special effects bounds
    if Assigned(clipPathEl) then
    begin
      ....
    end
    else if Assigned(maskEl) then
    begin
      ....
    end else
    begin
      clipRec := drawDat.bounds;
      // add this //////////////////
      if clipRec.IsEmpty and
        (drawDat.fontInfo.textLength > 0) and
        (self is TSubtextElement) then
      begin
        clipRec.Left := fParent.elRectWH.left.rawVal;
        clipRec.Bottom := fParent.elRectWH.top.rawVal;
        clipRec.Right := clipRec.Left + drawDat.fontInfo.textLength;
        clipRec.Top := clipRec.Bottom - drawDat.fontInfo.size;
      end;
      //////////////////////////////
```

**Comment by jfudickar** [comment]
Yes seems to fix it.
Nice. 
And thanks!!!

**Comment by jfudickar** [comment]
After upgrading to v4 the problem is back :-(

**Comment by jfudickar** [comment]
Adding the line fixes it again !

**Comment by carloBarazzetta** [comment]
Oh, sorry, but I've aligned Image32 source code of @AngusJohnson retrieved from His Gitub repo, probably it was not updated...

**Comment by AngusJohnson** [comment]
I've just updated the [Image32 repository](https://github.com/AngusJohnson/Image32) and the fix above has been included.
