### ISSUE TITLE
MultiSystem FMX

### ISSUE THREAD

**Issue by ange007** [EtheaDev/SVGIconImageList#45]
Hi.
Do you have plans for a support another system in FMX version?
Or used SVG library work only on Windows?

**Comment by carloBarazzetta** [comment]
There is a plan to make the svg rendering engine replaceable, to use native Direct2D support to SVG (alway in Windows).
Personally I've not a plan to extend the FMX version to other platforms.
A similar solution can be https://github.com/EtheaDev/IconFontsImageList that supports Android

**Comment by carloBarazzetta** [comment]
The goal of these components is precisely to avoid having to create images of various sizes (eg. Png), as we are forced to do today without the support of a vector library such as SVG.
It doesn't make much sense to me.
When we can replace the SVG engine and use one that is compatible with Android / iOS, this will be done.

**Comment by MHumm** [comment]
I'd find an Android compatible version useful as well. Doesn't FMX TPath mostly use a SVG compatible technology internally anyway?

**Comment by carloBarazzetta** [comment]
@ange007 : there is a new version of components (2.3.0) that uses a new engine Image32 that is compatible also with Android and iOS. I've not tested yet with Android and iOS, is not my primary business platform, but the FMX version of SVGIconsImageList now uses this new library that can be used also on Android and don't need windows units:
http://www.angusj.com/delphi/image32/Docs/Examples.htm
Please give me a feedback if you can try.
I'm closing this issue because we can continue to discuss / check FMX compatibility in issue #130
