### ISSUE TITLE
Separate storage from drawing of icons

### ISSUE THREAD

**Issue by pyscripter** [EtheaDev/SVGIconImageList#5]
Excellent work!

An ImageList is typically shared by more than one forms.  In a per-monitor DPI scaled appliation, every form should have its own imagelist so that icons are scaled according to the  monitor the form resides.  As it stands that would lead to icon duplication.

Delphi has solved this issue by having a separate TImageCollection that handles the storage of the icons and a VirtualImageList that draws icons from an ImageCollection appropriately scaled.

I suggest something similar.  a TSvgIconCollection that stores the svg icons and a TVirtualImageList that transforms a subset of icons from a TSvgIconCollection into a scaled ImageList.

**Comment by carloBarazzetta** [comment]
This component is backward compatible from XE6: for this reason it's built from TCustomImageList.
Actually the component rescale automatically, if you are using D10_3.
The possibility of having a TSVGIconCollection to use into a TVirtualImageList may be available in future.

**Comment by vincentparrett** [comment]
I'd be keen to see this, I started using TVirtualImageList etc (well my own version, since the default breaks drag and drop) but it's just getting to be too much work to organise several thousand images in multiple sizes, generate resources etc - svg would be a whole lot simpler. but as @pyscripter  says, storage and rendering need to be split up.
