### ISSUE TITLE
Rendering of some SVG images is incorrect

### ISSUE THREAD

**Issue by MarkRSill** [EtheaDev/SVGIconImageList#6]
90% of my SVG icons are rendering correctly, but that last 10% is holding me back from being able to use the library.  I've tried hard to debug the reason, but have been unsuccessful so far.  I have examples attached and show rendering by DevExpress and SVGIconImageList.  Correcting the anomalies will make this library a must have in today's high res world.
[SVGExamples.zip](https://github.com/EtheaDev/SVGIconImageList/files/4781407/SVGExamples.zip)

**Comment by carloBarazzetta** [comment]
Debugging the library (which was written by Martin Walter) is not easy, I will try to look at the examples you sent me to check if the solution is not too complex, but I cannot promise you anything at the moment.
Are you using the last version 1.5?

**Comment by MarkRSill** [comment]
Yes, this was with the latest version.  I will continue as well comparing a walk through the source of DevExpress and Martin's implementation.  I'm hoping it too is a simple issue that fixes what I'm seeing.  Thanks for your efforts, this is a great component.

**Comment by carloBarazzetta** [comment]
Hi Mark, I did some tests with your icons: the problem of the wrong "stroke" could be solved by changing this line of code into TSVGBasic.GetFillColor:
Result := INHERIT; 
instead of
Result := 0;
Can you try this fix and check if resolve many problems?

The problem inside Cleanup.svg is more complex because the library had some problems inside "transform" command.

**Comment by carloBarazzetta** [comment]
Resolved into 1.7 version.
