### ISSUE TITLE
Problem rendering material design icons

### ISSUE THREAD

**Issue by carloBarazzetta** [EtheaDev/SVGIconImageList#77]
With {.$DEFINE PreferNativeSvgSupport}
![image](https://user-images.githubusercontent.com/7803548/91287686-5a07f800-e790-11ea-8afe-7c3239ff5470.png)

With {$DEFINE PreferNativeSvgSupport}
![image](https://user-images.githubusercontent.com/7803548/91287892-9e939380-e790-11ea-8559-00ac3feb9d76.png)

@pyscripter : I remember that this problem was fixed..

repository of icons: https://github.com/Templarian/MaterialDesign.git

**Comment by pyscripter** [comment]
Are you sure about the problem being fixed before?  I do not recall.  It might help if you trace the commit.  

I have not changed the path code much except for the Quadratic Bezier curves (Q q T commands).  This one is using Arcs.

There are still issues with the path elements which might take time to fix since the code is complex.

**Comment by pyscripter** [comment]
Could you please the following:

procedure TSVGPathMove.AddToPath(Path: TGPGraphicsPath);
begin
  Path.CloseFigure;  // added
  Path.StartFigure;
end;

Before committing can you test whether this does not break anything else.

**Comment by carloBarazzetta** [comment]
Yes, it seems to fix all the problems in material design icons!
