### ISSUE TITLE
Proposal: version 2.1

### ISSUE THREAD

**Issue by carloBarazzetta** [EtheaDev/SVGIconImageList#99]
Since the release of 2.0, many fixes and improvements have been made: are we ready to release a new version 2.1 now?
@pyscripter and @vincentparrett What's your opinion?

**Comment by pyscripter** [comment]
I am just doing a couple of more improvements.  So please wait a bit.

**Comment by carloBarazzetta** [comment]
> I am just doing a couple of more improvements. So please wait a bit.

OK!

**Comment by vincentparrett** [comment]
No objections here, if you follow [semantic versioning](https://semver.org/) then this next release would fall under

" add functionality in a backwards compatible manner" 

The interface changes are minor and backwards compatible.

**Comment by TextEditorPro** [comment]
Have you thought about caching of images? I tested this in my application and it is remarkably slow compared to my current TsCharImageList/TsVirtualImageList solution. I guess the images are not cached?

**Comment by vincentparrett** [comment]
The images are 'cached' - the svg's are rendered into bitmaps stored in windows imagelist object - the only time they are re-rendered is when the size changes or the dpi changes (for the virtualimagelist). 

When you say it's slow do you mean in the demo? I have notices that changing the size is sluggish, but that's due to using a slider which results in lots of size changes before getting to the desired size. That could be improved by using dropdown  or something else to select the size.

**Comment by TextEditorPro** [comment]
Ok, I will check the code why it is so slow.

No, I didn't mean the demo. I meant my own application. There were about 15-20 icons to paint.

**Comment by carloBarazzetta** [comment]
I've updated packages for 10.4.1: are we ready for 2.1?

**Comment by TextEditorPro** [comment]
That slowness is AlphaSkins issue - it skips its own caching. I have to fix quite a lot of code to support this.

**Comment by carloBarazzetta** [comment]
A question for @pyscripter : in version 2.1 we want to maintain default engine to Direct2D or switch to TSVG?

**Comment by pyscripter** [comment]
Not sure.  What do you think?  There may still be rendering issues with TSVG (see #104), but you get text and styles.  It is up to you.

**Comment by carloBarazzetta** [comment]
Version 2.1 generated.
